name: clinic_management_app
description: تطبيق إدارة العيادة الطبية
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1  # لإدارة حالة التطبيق
  http: ^0.13.3  # لإجراء طلبات HTTP
  shared_preferences: ^2.0.9  # للوصول إلى تخزين البيانات المحلية
  flutter_secure_storage: ^4.2.1  # لتخزين المعلومات الحساسة بشكل آمن
  intl: ^0.17.0  # لدعم اللغات وتنسيق التواريخ والأرقام
  flutter_svg: ^0.23.0  # لعرض الصور SVG
  flutter_spinkit: ^5.1.0  # لإضافة مؤثرات تحميل
  fluttertoast: ^8.0.8  # لعرض رسائل تنبيه
  sqflite: ^2.3.2
  path_provider: ^2.0.2
http: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
